# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title 

highlighter: true

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Ajey Gore
tagline: "Code, Deploy, Automate"
author :
  name : Ajey Gore
  email : ajeygore@gmail.com
  github : ajeygore
  twitter : ajeygore
  feedburner : ajeygore

domain: ajeygore.in
author: Ajey Gore
email: ajey@codeigition.co
title: Ajey Gore

production_url : http://ajeygore.github.com

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
- changelog.md
- .rvmrc
- .rbenv-version


include:
- _stylesheets
- _javascript

markdown: rdiscount

sass:
  sass_dir: assets/vendor/
  style: :compressed

# Custom site configuration
lang: en
