
# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : Ajey Gore
tagline: "Ideate, Implement, Iterate"
author :
  name : Ajey Gore
  email : ajeygore@gmail.com
  github : ajeygore
  twitter : ajeygore
  feedburner : ajeygore

lead_image: ajey_gore_website_card.png
description: A site about product and software engineering. Read & Discover about building teams, org and impactful software products.
domain: ajeygore.in
incremental: true

production_url : https://ajeygore.in
collections_dir: collections

# This is the default format. 
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
highlighter: rouge

collections:
  posts:
    output: true
    permalink: /content/:title

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor
- changelog.md
- .rvmrc
- .rbenv-version

include:
- assets

markdown: kramdown

# Custom site configuration
lang: en
